// Per-test case descriptions for the Sandbox screen's detail panel.
// One entry per real it() block in vitest, plus e2e flows.
// Authored by reading the actual test file — do not fabricate entries.

export type TestCaseType = 'unit' | 'integration' | 'e2e';

export interface TestCase {
  /** Matches the it() description or the e2e flow name. */
  name: string;
  /** Plain-English explanation of what this test guarantees (owner-readable). */
  what: string;
  type: TestCaseType;
}

/** TEST_CASES[groupId] = array of TestCase for that group. */
export const TEST_CASES: Record<string, TestCase[]> = {
  'sales-pos': [
    // ── Pure utility ──────────────────────────────────────────────────────────
    {
      name: 'computeLoyaltyEarned — floors netTotal / 100',
      what:
        'Loyalty points earned are exactly the integer part of (net total ÷ 100) in LKR — ' +
        'LKR 1 099 earns 10 pts, LKR 1 100 earns 11 pts, LKR 0 earns 0.',
      type: 'unit',
    },
    {
      name: 'computeRedemptionValue — 1 point = LKR 1',
      what:
        'Each loyalty point redeemed is worth exactly LKR 1. ' +
        '250 points knocks LKR 250 off the total; 0 points changes nothing.',
      type: 'unit',
    },
    // ── Happy path ────────────────────────────────────────────────────────────
    {
      name: 'returns invoiceId, invoiceNo, and earnedPoints on success',
      what:
        'A complete checkout returns the database invoice UUID, a formatted invoice number ' +
        '(INV-XXXXXX), and the loyalty points earned from the net total.',
      type: 'unit',
    },
    {
      name: 'passes wholesale mode to checkout_sale RPC',
      what:
        'When the sale is flagged as wholesale, the "wholesale" mode string reaches the ' +
        'atomic checkout RPC — so the invoice is stored correctly for B2B reporting.',
      type: 'unit',
    },
    {
      name: 'passes retail mode when isWholesale=false',
      what:
        'When isWholesale is false, the RPC receives "retail" mode — ' +
        'ensuring walk-in and retail customers are always on the right price tier.',
      type: 'unit',
    },
    {
      name: 'invoice number matches INV-XXXXXX format',
      what:
        'Every invoice number generated by the service matches the INV-XXXXXX format ' +
        '(INV- followed by exactly 6 digits), keeping the numbering scheme consistent.',
      type: 'unit',
    },
    // ── Payment status ────────────────────────────────────────────────────────
    {
      name: 'sets payment_status "paid" when splits cover the total',
      what:
        'If the sum of payment splits equals the invoice total, the invoice is marked "paid" ' +
        'so the customer ledger is immediately cleared.',
      type: 'unit',
    },
    {
      name: 'sets payment_status "partial" when splits partially cover total',
      what:
        'If payment splits cover only part of the total, the invoice is "partial" — ' +
        'the outstanding balance is updated but the debt is not written off.',
      type: 'unit',
    },
    {
      name: 'sets payment_status "unpaid" when no payment splits',
      what:
        'If no payment is collected at the counter (pure credit sale), the invoice is ' +
        '"unpaid" and the full amount adds to the customer\'s outstanding balance.',
      type: 'unit',
    },
    // ── Walk-in ───────────────────────────────────────────────────────────────
    {
      name: 'walk-in customer: skips credit check and returns earnedPoints=0',
      what:
        'Walk-in (null customerId) sales bypass the credit limit check entirely and earn ' +
        '0 loyalty points — no customer record to link points to.',
      type: 'unit',
    },
    // ── Loyalty ───────────────────────────────────────────────────────────────
    {
      name: 'deducts redemption value from netTotal before computing earnedPoints',
      what:
        'When a customer redeems loyalty points, the points value (in LKR) is subtracted ' +
        'from the total before earning new points — so customers earn on what they actually paid.',
      type: 'unit',
    },
    {
      name: 'clamps netTotal to 0 if redemption value exceeds total',
      what:
        'If a customer tries to redeem more points than the order is worth, the net total ' +
        'floors at LKR 0 (no negative invoices) and 0 new points are earned.',
      type: 'unit',
    },
    // ── Stock validation ──────────────────────────────────────────────────────
    {
      name: 'throws "Insufficient stock" before calling the RPC when stock is low',
      what:
        'If the cart wants more units than the shop stock holds, checkout stops before ' +
        'the database is ever asked to record the sale — no orphaned invoice is created.',
      type: 'unit',
    },
    {
      name: 'throws when shop_stock query itself fails',
      what:
        'A database error reading stock availability surfaces as "Failed to validate stock" — ' +
        'the sale is blocked rather than proceeding with unknown stock levels.',
      type: 'unit',
    },
    {
      name: 'treats missing stock row as 0 available',
      what:
        'A product with no stock_batches row is treated as having 0 units — ' +
        'the sale is blocked with "Insufficient stock" rather than silently over-selling.',
      type: 'unit',
    },
    {
      name: 'skips a cart item with 0 total pieces in stock deduction loop',
      what:
        'Cart items with zero quantity (0 cartons, 0 pieces) are silently skipped in the ' +
        'FIFO deduction loop so zero-qty placeholders never corrupt stock levels.',
      type: 'unit',
    },
    // ── Credit limit ──────────────────────────────────────────────────────────
    {
      name: 'throws "Credit limit exceeded" when outstanding would breach limit',
      what:
        'If recording this sale on credit would push the customer\'s outstanding balance over ' +
        'their credit limit, checkout is blocked before anything is written to the database.',
      type: 'unit',
    },
    {
      name: 'skips credit check for walk-in customer even with outstanding',
      what:
        'Walk-in sales (null customerId) never trigger the credit limit check — ' +
        'there is no customer account to enforce a limit against.',
      type: 'unit',
    },
    // ── RPC failure ───────────────────────────────────────────────────────────
    {
      name: 'throws "Checkout failed" when checkout_sale RPC returns an error',
      what:
        'If the atomic checkout RPC fails (e.g. unique-constraint on invoice_no), the error ' +
        'message surfaces as "Checkout failed: …" — no silent data loss.',
      type: 'unit',
    },
    // ── Deduction routing ─────────────────────────────────────────────────────
    {
      name: 'calls deduct_stock_from_batch when item has a batchId',
      what:
        'When a cart item specifies a particular batch (scanned barcode), stock is deducted ' +
        'from that exact batch rather than via FIFO — giving precise batch traceability.',
      type: 'unit',
    },
    {
      name: 'calls deduct_stock_fifo when item has no batchId',
      what:
        'When no batch is specified, stock is deducted oldest-first (FIFO) to minimise ' +
        'ageing stock and keep the inventory cost calculation accurate.',
      type: 'unit',
    },
    {
      name: 'throws when deduct_stock_fifo returns an error (no longer silently swallowed)',
      what:
        'A FIFO deduction failure (e.g. batch not found mid-sale) now surfaces as an error ' +
        'instead of being swallowed — the operator is told, not left with mismatched stock.',
      type: 'unit',
    },
    {
      name: 'throws when deduct_stock_from_batch returns an error',
      what:
        'A batch deduction failure (e.g. batch locked or deleted) surfaces as an error — ' +
        'the sale is flagged so stock counts stay in sync with physical inventory.',
      type: 'unit',
    },
    // ── Multi-item ────────────────────────────────────────────────────────────
    {
      name: 'calls deduct_stock_fifo once per unique item in cart',
      what:
        'Multi-product carts trigger one FIFO deduction call per unique product, ' +
        'with the correct unit count, so every line item is reflected in stock.',
      type: 'unit',
    },
    // ── Payment splits ────────────────────────────────────────────────────────
    {
      name: 'filters out zero-amount splits before passing to RPC',
      what:
        'Payment splits with a LKR 0 amount are stripped before the RPC is called — ' +
        'so split-tender receipts never record ghost payment rows.',
      type: 'unit',
    },
    {
      name: 'passes all payment splits correctly including cheque fields',
      what:
        'Split payments that include a cheque correctly forward cheque_number and bank_name ' +
        'to the RPC so the cheque lifecycle (pending → cleared) can be tracked.',
      type: 'unit',
    },
    // ── checkCreditLimit standalone ───────────────────────────────────────────
    {
      name: 'checkCreditLimit — returns ok=true when credit is available',
      what:
        'If the customer\'s outstanding balance plus the new sale stays within their credit ' +
        'limit, the check passes and the sale proceeds.',
      type: 'unit',
    },
    {
      name: 'checkCreditLimit — returns ok=false with message when limit would be exceeded',
      what:
        'If the sale would push the customer over their credit limit, the check returns ' +
        'ok=false with a human-readable message showing the LKR shortfall.',
      type: 'unit',
    },
    {
      name: 'checkCreditLimit — returns ok=true when customer fetch fails (fail open)',
      what:
        'If the customer record cannot be fetched (network error, deleted record), the credit ' +
        'check fails open (ok=true) so a transient DB blip cannot block all sales.',
      type: 'unit',
    },
    // ── E2E ───────────────────────────────────────────────────────────────────
    {
      name: 'pos-checkout (E2E)',
      what:
        'Full end-to-end checkout: add items to cart, split payment, confirm the invoice ' +
        'appears in the sales list and stock counts decrease correctly.',
      type: 'e2e',
    },
  ],

  'products-inventory': [
    {
      name: 'seed contains 12 products in sandbox schema',
      what:
        'After sandbox reset + reseed, exactly 12 products with the fixed b1000000-… UUIDs exist — ' +
        'confirming the seed script ran completely.',
      type: 'integration',
    },
    {
      name: 'seed contains 12 stock batches (one per product)',
      what:
        'After sandbox reset + reseed, exactly 12 stock_batches rows with the fixed e1000000-… UUIDs ' +
        'exist — verifying the seed correctly stocked every product.',
      type: 'integration',
    },
    {
      name: 'Bluetooth Headphones batch has expected carton + loose_pieces count',
      what:
        'The seeded batch for "Bluetooth Headphones" has cartons=2 and loose_pieces=4, matching ' +
        'the seed script — so quantity reads are consistent after reset.',
      type: 'integration',
    },
    {
      name: 'stock adjustment insert increases aggregate adjustment_pieces',
      what:
        'Inserting a positive stock adjustment for a product increases the SUM(adjustment_pieces) ' +
        'for that product by the inserted amount — the adjustment table is writable from tests.',
      type: 'integration',
    },
    {
      name: 'negative stock adjustment represents sold / deducted units',
      what:
        'Inserting a negative adjustment correctly decreases the running total — confirming that ' +
        'stock deductions (sales, returns) reduce available inventory through the adjustments table.',
      type: 'integration',
    },
  ],

  'customers-credit': [
    {
      name: 'recordPayment — calls record_payment_atomic RPC with correct params for cash',
      what:
        'A cash payment calls the record_payment_atomic RPC with p_customer_id, p_invoice_id, ' +
        'p_amount, p_method="cash", and empty strings for cheque fields.',
      type: 'unit',
    },
    {
      name: 'recordPayment — passes cheque fields when method is cheque',
      what:
        'When method is "cheque", bank_name, cheque_number, and due_date are forwarded to the ' +
        'RPC so the cheque lifecycle can be tracked from receipt.',
      type: 'unit',
    },
    {
      name: 'recordPayment — accepts null invoiceId for unallocated credit payments',
      what:
        'Passing null as invoiceId records an unallocated credit against the customer ' +
        'without requiring a specific invoice — useful for advance deposits.',
      type: 'unit',
    },
    {
      name: 'recordPayment — throws when RPC returns error',
      what:
        'When the record_payment_atomic RPC signals an error (e.g. insufficient balance, DB constraint), ' +
        'the service surfaces it as a thrown error rather than silently failing.',
      type: 'unit',
    },
    {
      name: 'getCustomerById — returns credit_limit and outstanding_balance',
      what:
        'Fetching a customer returns their credit_limit and outstanding_balance — ' +
        'the two fields that drive credit enforcement at the POS.',
      type: 'unit',
    },
    {
      name: 'getCustomerById — throws when supabase returns an error',
      what:
        'If the customer fetch fails (row not found, permission denied), the error propagates ' +
        'so the caller can show the right message instead of receiving null data.',
      type: 'unit',
    },
    {
      name: 'createCustomer — always initialises outstanding_balance to 0',
      what:
        'New customers always start with an outstanding_balance of 0, regardless of any balance ' +
        'in the input — they begin with a clean slate.',
      type: 'unit',
    },
  ],

  'refunds-returns': [
    {
      name: 'throws "already been returned" when invoice notes contain [RETURNED]',
      what:
        'If the invoice was previously returned (notes include the [RETURNED] tag), the service ' +
        'blocks a second return rather than creating a duplicate credit.',
      type: 'unit',
    },
    {
      name: 'throws "no items to return" when invoice_items is empty',
      what:
        'An invoice with no line items cannot be returned — the service throws before touching ' +
        'stock or payments, preventing zero-value return records.',
      type: 'unit',
    },
    {
      name: 'throws "Invoice not found" when supabase fetch returns error',
      what:
        'If the invoice fetch itself fails (not found, network), the service throws immediately ' +
        'with the underlying DB error message.',
      type: 'unit',
    },
    {
      name: 'inserts one stock adjustment per line item',
      what:
        'For each invoice line item, a positive stock_adjustment is inserted so the returned ' +
        'goods re-enter inventory — no items are silently skipped.',
      type: 'unit',
    },
    {
      name: 'throws when stock adjustment insertion fails',
      what:
        'A DB error inserting stock adjustments surfaces as a thrown error — the return is blocked ' +
        'rather than proceeding with mismatched stock levels.',
      type: 'unit',
    },
    {
      name: 'inserts a negative payment for a paid invoice',
      what:
        'When a paid invoice is returned (method ≠ no_refund), a negative payment record is created ' +
        'so the customer ledger correctly shows the refund.',
      type: 'unit',
    },
    {
      name: 'inserts a negative payment for a partial invoice',
      what:
        'Partial-payment invoices also receive a negative payment on return — ' +
        'the refunded amount equals the full invoice total regardless of how much was paid.',
      type: 'unit',
    },
    {
      name: 'skips payment insertion for unpaid invoice with no_refund method',
      what:
        'When the invoice was never paid and the return method is no_refund, no payment record ' +
        'is created — the return is purely a stock restoration.',
      type: 'unit',
    },
    {
      name: 'skips payment insertion for paid invoice when refund method is no_refund',
      what:
        'Even for paid invoices, choosing no_refund suppresses the payment insertion — ' +
        'useful when goods are exchanged rather than refunded.',
      type: 'unit',
    },
    {
      name: 'throws when payment insertion fails',
      what:
        'A DB error inserting the refund payment surfaces as a thrown error — ' +
        'the operator is alerted rather than leaving the ledger inconsistent.',
      type: 'unit',
    },
    {
      name: 'queries and updates customer outstanding_balance for credit_note refund',
      what:
        'For credit_note returns, the customer\'s outstanding_balance is reduced by the invoice ' +
        'total — they accumulate store credit instead of receiving cash.',
      type: 'unit',
    },
    {
      name: 'updates invoice notes with [RETURNED] tag',
      what:
        'The invoice record is stamped with a [RETURNED] tag in its notes, preventing double-returns ' +
        'and giving the owner an audit trail with the return timestamp.',
      type: 'unit',
    },
  ],

  'payments-cheques': [
    {
      name: 'depositCheque — calls update_cheque_status RPC with "processing"',
      what:
        'Depositing a cheque transitions it to "processing" via the update_cheque_status RPC, ' +
        'signalling the cheque has been submitted to the bank.',
      type: 'unit',
    },
    {
      name: 'depositCheque — throws when RPC rejects the transition',
      what:
        'If the RPC signals an invalid transition (e.g. cheque already deposited), ' +
        'the error propagates so the UI can show the correct message.',
      type: 'unit',
    },
    {
      name: 'completeCheque — calls update_cheque_status RPC with "completed"',
      what:
        'Marking a cheque as cleared transitions it to "completed" — the customer\'s debt ' +
        'for that cheque is formally settled.',
      type: 'unit',
    },
    {
      name: 'completeCheque — throws when RPC rejects the transition',
      what:
        'An invalid transition (e.g. cheque was already completed or returned) is surfaced as ' +
        'an error — no silent state corruption.',
      type: 'unit',
    },
    {
      name: 'returnCheque — calls update_cheque_status RPC with "returned"',
      what:
        'Bouncing a cheque transitions it to "returned" — the owner knows to follow up ' +
        'with the customer for an alternative payment.',
      type: 'unit',
    },
    {
      name: 'returnCheque — throws when RPC rejects the transition',
      what:
        'An invalid bounce transition is surfaced as an error rather than silently succeeding.',
      type: 'unit',
    },
    {
      name: 'three functions send three distinct target statuses',
      what:
        'depositCheque, completeCheque, and returnCheque each send a different p_new_status value ' +
        'to the RPC — "processing", "completed", and "returned" are all distinct and non-overlapping.',
      type: 'unit',
    },
  ],

  'sandbox': [
    {
      name: 'sandbox isolation — reset_all() leaves public schema row counts unchanged',
      what:
        'Running sandbox.reset_all() + reseed never alters public.products, ' +
        'public.customers, or public.invoices row counts — public data is fully protected.',
      type: 'integration',
    },
    {
      name: 'sandbox isolation — sandbox.app_meta.schema_marker is "sandbox"',
      what:
        'After a reset, the sandbox schema marker remains "sandbox" — confirming the ' +
        'app_meta row survived truncation (it is excluded from reset_all).',
      type: 'integration',
    },
    {
      name: 'sandbox isolation — seeded sandbox product exists after reset',
      what:
        'After reset + reseed, the fixed-UUID "Bluetooth Headphones" product exists — ' +
        'verifying the seed script ran and the fixed UUIDs are stable.',
      type: 'integration',
    },
    {
      name: 'sandbox isolation — seeded sandbox Walk-in Customer exists after reset',
      what:
        'After reset + reseed, the fixed-UUID Walk-in Customer exists — ' +
        'confirming the mandatory baseline customer is always present for POS checkout.',
      type: 'integration',
    },
    {
      name: 'test-groups precision contract — every test file is in exactly one group',
      what:
        'Every src/**/*.test.{ts,tsx} on disk appears in exactly one group\'s vitestFiles, ' +
        'and every listed path actually exists — the catalog can never silently fall out of date.',
      type: 'unit',
    },
    {
      name: 'test-groups precision contract — every listed vitestFiles path resolves to a real file',
      what:
        'Each path in any group\'s vitestFiles exists on disk — no stale entries after ' +
        'test files are renamed or deleted.',
      type: 'unit',
    },
  ],
};
