// Per-test case descriptions for the Sandbox screen's detail panel.
// One entry per real it() block in vitest, plus e2e flows.
// Authored by reading the actual test file — do not fabricate entries.

export type TestCaseType = 'unit' | 'integration' | 'e2e';

export interface TestCase {
  /** Matches the it() description or the e2e flow name. */
  name: string;
  /** Plain-English explanation of what this test guarantees (owner-readable). */
  what: string;
  type: TestCaseType;
}

/** TEST_CASES[groupId] = array of TestCase for that group. */
export const TEST_CASES: Record<string, TestCase[]> = {
  'sales-pos': [
    // ── Pure utility ──────────────────────────────────────────────────────────
    {
      name: 'computeLoyaltyEarned — floors netTotal / 100',
      what:
        'Loyalty points earned are exactly the integer part of (net total ÷ 100) in LKR — ' +
        'LKR 1 099 earns 10 pts, LKR 1 100 earns 11 pts, LKR 0 earns 0.',
      type: 'unit',
    },
    {
      name: 'computeRedemptionValue — 1 point = LKR 1',
      what:
        'Each loyalty point redeemed is worth exactly LKR 1. ' +
        '250 points knocks LKR 250 off the total; 0 points changes nothing.',
      type: 'unit',
    },
    // ── Happy path ────────────────────────────────────────────────────────────
    {
      name: 'returns invoiceId, invoiceNo, and earnedPoints on success',
      what:
        'A complete checkout returns the database invoice UUID, a formatted invoice number ' +
        '(INV-XXXXXX), and the loyalty points earned from the net total.',
      type: 'unit',
    },
    {
      name: 'passes wholesale mode to checkout_sale RPC',
      what:
        'When the sale is flagged as wholesale, the "wholesale" mode string reaches the ' +
        'atomic checkout RPC — so the invoice is stored correctly for B2B reporting.',
      type: 'unit',
    },
    {
      name: 'passes retail mode when isWholesale=false',
      what:
        'When isWholesale is false, the RPC receives "retail" mode — ' +
        'ensuring walk-in and retail customers are always on the right price tier.',
      type: 'unit',
    },
    {
      name: 'invoice number matches INV-XXXXXX format',
      what:
        'Every invoice number generated by the service matches the INV-XXXXXX format ' +
        '(INV- followed by exactly 6 digits), keeping the numbering scheme consistent.',
      type: 'unit',
    },
    // ── Payment status ────────────────────────────────────────────────────────
    {
      name: 'sets payment_status "paid" when splits cover the total',
      what:
        'If the sum of payment splits equals the invoice total, the invoice is marked "paid" ' +
        'so the customer ledger is immediately cleared.',
      type: 'unit',
    },
    {
      name: 'sets payment_status "partial" when splits partially cover total',
      what:
        'If payment splits cover only part of the total, the invoice is "partial" — ' +
        'the outstanding balance is updated but the debt is not written off.',
      type: 'unit',
    },
    {
      name: 'sets payment_status "unpaid" when no payment splits',
      what:
        'If no payment is collected at the counter (pure credit sale), the invoice is ' +
        '"unpaid" and the full amount adds to the customer\'s outstanding balance.',
      type: 'unit',
    },
    // ── Walk-in ───────────────────────────────────────────────────────────────
    {
      name: 'walk-in customer: skips credit check and returns earnedPoints=0',
      what:
        'Walk-in (null customerId) sales bypass the credit limit check entirely and earn ' +
        '0 loyalty points — no customer record to link points to.',
      type: 'unit',
    },
    // ── Loyalty ───────────────────────────────────────────────────────────────
    {
      name: 'deducts redemption value from netTotal before computing earnedPoints',
      what:
        'When a customer redeems loyalty points, the points value (in LKR) is subtracted ' +
        'from the total before earning new points — so customers earn on what they actually paid.',
      type: 'unit',
    },
    {
      name: 'clamps netTotal to 0 if redemption value exceeds total',
      what:
        'If a customer tries to redeem more points than the order is worth, the net total ' +
        'floors at LKR 0 (no negative invoices) and 0 new points are earned.',
      type: 'unit',
    },
    // ── Stock validation ──────────────────────────────────────────────────────
    {
      name: 'throws "Insufficient stock" before calling the RPC when stock is low',
      what:
        'If the cart wants more units than the shop stock holds, checkout stops before ' +
        'the database is ever asked to record the sale — no orphaned invoice is created.',
      type: 'unit',
    },
    {
      name: 'throws when shop_stock query itself fails',
      what:
        'A database error reading stock availability surfaces as "Failed to validate stock" — ' +
        'the sale is blocked rather than proceeding with unknown stock levels.',
      type: 'unit',
    },
    {
      name: 'treats missing stock row as 0 available',
      what:
        'A product with no stock_batches row is treated as having 0 units — ' +
        'the sale is blocked with "Insufficient stock" rather than silently over-selling.',
      type: 'unit',
    },
    {
      name: 'skips a cart item with 0 total pieces in stock deduction loop',
      what:
        'Cart items with zero quantity (0 cartons, 0 pieces) are silently skipped in the ' +
        'FIFO deduction loop so zero-qty placeholders never corrupt stock levels.',
      type: 'unit',
    },
    // ── Credit limit ──────────────────────────────────────────────────────────
    {
      name: 'throws "Credit limit exceeded" when outstanding would breach limit',
      what:
        'If recording this sale on credit would push the customer\'s outstanding balance over ' +
        'their credit limit, checkout is blocked before anything is written to the database.',
      type: 'unit',
    },
    {
      name: 'skips credit check for walk-in customer even with outstanding',
      what:
        'Walk-in sales (null customerId) never trigger the credit limit check — ' +
        'there is no customer account to enforce a limit against.',
      type: 'unit',
    },
    // ── RPC failure ───────────────────────────────────────────────────────────
    {
      name: 'throws "Checkout failed" when checkout_sale RPC returns an error',
      what:
        'If the atomic checkout RPC fails (e.g. unique-constraint on invoice_no), the error ' +
        'message surfaces as "Checkout failed: …" — no silent data loss.',
      type: 'unit',
    },
    // ── Deduction routing ─────────────────────────────────────────────────────
    {
      name: 'calls deduct_stock_from_batch when item has a batchId',
      what:
        'When a cart item specifies a particular batch (scanned barcode), stock is deducted ' +
        'from that exact batch rather than via FIFO — giving precise batch traceability.',
      type: 'unit',
    },
    {
      name: 'calls deduct_stock_fifo when item has no batchId',
      what:
        'When no batch is specified, stock is deducted oldest-first (FIFO) to minimise ' +
        'ageing stock and keep the inventory cost calculation accurate.',
      type: 'unit',
    },
    {
      name: 'throws when deduct_stock_fifo returns an error (no longer silently swallowed)',
      what:
        'A FIFO deduction failure (e.g. batch not found mid-sale) now surfaces as an error ' +
        'instead of being swallowed — the operator is told, not left with mismatched stock.',
      type: 'unit',
    },
    {
      name: 'throws when deduct_stock_from_batch returns an error',
      what:
        'A batch deduction failure (e.g. batch locked or deleted) surfaces as an error — ' +
        'the sale is flagged so stock counts stay in sync with physical inventory.',
      type: 'unit',
    },
    // ── Multi-item ────────────────────────────────────────────────────────────
    {
      name: 'calls deduct_stock_fifo once per unique item in cart',
      what:
        'Multi-product carts trigger one FIFO deduction call per unique product, ' +
        'with the correct unit count, so every line item is reflected in stock.',
      type: 'unit',
    },
    // ── Payment splits ────────────────────────────────────────────────────────
    {
      name: 'filters out zero-amount splits before passing to RPC',
      what:
        'Payment splits with a LKR 0 amount are stripped before the RPC is called — ' +
        'so split-tender receipts never record ghost payment rows.',
      type: 'unit',
    },
    {
      name: 'passes all payment splits correctly including cheque fields',
      what:
        'Split payments that include a cheque correctly forward cheque_number and bank_name ' +
        'to the RPC so the cheque lifecycle (pending → cleared) can be tracked.',
      type: 'unit',
    },
    // ── checkCreditLimit standalone ───────────────────────────────────────────
    {
      name: 'checkCreditLimit — returns ok=true when credit is available',
      what:
        'If the customer\'s outstanding balance plus the new sale stays within their credit ' +
        'limit, the check passes and the sale proceeds.',
      type: 'unit',
    },
    {
      name: 'checkCreditLimit — returns ok=false with message when limit would be exceeded',
      what:
        'If the sale would push the customer over their credit limit, the check returns ' +
        'ok=false with a human-readable message showing the LKR shortfall.',
      type: 'unit',
    },
    {
      name: 'checkCreditLimit — returns ok=true when customer fetch fails (fail open)',
      what:
        'If the customer record cannot be fetched (network error, deleted record), the credit ' +
        'check fails open (ok=true) so a transient DB blip cannot block all sales.',
      type: 'unit',
    },
    // ── E2E ───────────────────────────────────────────────────────────────────
    {
      name: 'pos-checkout (E2E)',
      what:
        'Full end-to-end checkout: add items to cart, split payment, confirm the invoice ' +
        'appears in the sales list and stock counts decrease correctly.',
      type: 'e2e',
    },
  ],

  'sandbox': [
    {
      name: 'sandbox isolation — reset_all() leaves public schema row counts unchanged',
      what:
        'Running sandbox.reset_all() + reseed never alters public.products, ' +
        'public.customers, or public.invoices row counts — public data is fully protected.',
      type: 'integration',
    },
    {
      name: 'sandbox isolation — sandbox.app_meta.schema_marker is "sandbox"',
      what:
        'After a reset, the sandbox schema marker remains "sandbox" — confirming the ' +
        'app_meta row survived truncation (it is excluded from reset_all).',
      type: 'integration',
    },
    {
      name: 'sandbox isolation — seeded sandbox product exists after reset',
      what:
        'After reset + reseed, the fixed-UUID "Bluetooth Headphones" product exists — ' +
        'verifying the seed script ran and the fixed UUIDs are stable.',
      type: 'integration',
    },
    {
      name: 'sandbox isolation — seeded sandbox Walk-in Customer exists after reset',
      what:
        'After reset + reseed, the fixed-UUID Walk-in Customer exists — ' +
        'confirming the mandatory baseline customer is always present for POS checkout.',
      type: 'integration',
    },
    {
      name: 'test-groups precision contract — every test file is in exactly one group',
      what:
        'Every src/**/*.test.{ts,tsx} on disk appears in exactly one group\'s vitestFiles, ' +
        'and every listed path actually exists — the catalog can never silently fall out of date.',
      type: 'unit',
    },
    {
      name: 'test-groups precision contract — every listed vitestFiles path resolves to a real file',
      what:
        'Each path in any group\'s vitestFiles exists on disk — no stale entries after ' +
        'test files are renamed or deleted.',
      type: 'unit',
    },
  ],
};
